tasks:
 - name: Setup django
   before: |
      export INVENTREE_DB_ENGINE='sqlite3'
      export INVENTREE_DB_NAME='/workspace/InvenTree/dev/database.sqlite3'
      export INVENTREE_MEDIA_ROOT='/workspace/InvenTree/inventree-data/media'
      export INVENTREE_STATIC_ROOT='/workspace/InvenTree/dev/static'
      export INVENTREE_BACKUP_DIR='/workspace/InvenTree/dev/backup'
      export PIP_USER='no'

      sudo apt install -y gettext
      python3 -m venv venv
      source venv/bin/activate
      pip install invoke pyyaml
      mkdir dev
      invoke update
      invoke setup-test --ignore-update --path inventree-data
      gp sync-done start_server

 - name: Start server
   init: gp sync-await start_server
   command: |
      gp sync-await start_server
      export INVENTREE_DB_ENGINE='sqlite3'
      export INVENTREE_DB_NAME='/workspace/InvenTree/dev/database.sqlite3'
      export INVENTREE_MEDIA_ROOT='/workspace/InvenTree/inventree-data/media'
      export INVENTREE_STATIC_ROOT='/workspace/InvenTree/dev/static'
      export INVENTREE_BACKUP_DIR='/workspace/InvenTree/dev/backup'

      source venv/bin/activate
      inv server

ports:
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    pullRequests: false
    pullRequestsFromForks: true
    addBadge: true
    addLabel: gitpod-ready
    addCheck: false
